### ISSUE TITLE
大佬，各个代码文件是干嘛的啊，没怎么看懂

### ISSUE THREAD

**Issue by freemedom** [NoCLin/localStorage-recovery#1]

**Comment by NoCLin** [comment]
抱歉，问题解决了吗？我才看到这个issue，一直没有提醒...

这几个脚本是在解析leveldb的快照日志

[ls_ldbdump.py](https://github.com/NoCLin/localStorage-recovery/blob/master/ls_ldbdump.py)  处理 ldbdump的结果

[ls_pyleveldb.py](https://github.com/NoCLin/localStorage-recovery/blob/master/ls_pyleveldb.py) 处理 pyleveldb的结果

如果还有问题可以随时issue留言或者邮件联系 Thanks

**Comment by freemedom** [comment]
我也记不太清了(°◇° )，太久了，当时好像试了一下没成功
